name: Generate Datas

on:
  schedule: 
    - cron: "0 */12 * * *"  # Execute every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: "20193663"
          svg_out_path: "dist/github-contribution-grid-snake.svg"

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Install svgexport
      - name: Install svgexport
        run: npm install -g svgexport

      # Convert SVG to GIF
      - name: Convert SVG to GIF
        run: svgexport dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake.gif gif

      # Adjust permissions for the output directory
      - name: Adjust permissions for output directory
        run: chmod -R 777 dist

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
