name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "*/12 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Run Platane/snk
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ secrets.GITHUB_USER_NAME }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif
      
      # Set SVG Output Path
      - name: Set SVG Output Path
        run: echo "SVG_OUT_PATH=dist/github-contribution-grid-snake.svg" >> $GITHUB_ENV

      # Set GIF Output Path
      - name: Set GIF Output Path
        run: echo "GIF_OUT_PATH=dist/github-contribution-grid-snake.gif" >> $GITHUB_ENV

      # Publish to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
